name: exchange
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.3.6

dev_dependencies:
  build_runner: ^2.4.4
  auto_route_generator: ^7.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
